/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HouseOfCraftRouteImport } from './routes/house-of-craft'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as ArtisansRouteImport } from './routes/artisans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalSlugRouteImport } from './routes/journal_.$slug'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseOfCraftRoute = HouseOfCraftRouteImport.update({
  id: '/house-of-craft',
  path: '/house-of-craft',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisansRoute = ArtisansRouteImport.update({
  id: '/artisans',
  path: '/artisans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal_/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artisans': typeof ArtisansRoute
  '/collection': typeof CollectionRoute
  '/house-of-craft': typeof HouseOfCraftRoute
  '/journal': typeof JournalRoute
  '/visit': typeof VisitRoute
  '/journal/$slug': typeof JournalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artisans': typeof ArtisansRoute
  '/collection': typeof CollectionRoute
  '/house-of-craft': typeof HouseOfCraftRoute
  '/journal': typeof JournalRoute
  '/visit': typeof VisitRoute
  '/journal/$slug': typeof JournalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artisans': typeof ArtisansRoute
  '/collection': typeof CollectionRoute
  '/house-of-craft': typeof HouseOfCraftRoute
  '/journal': typeof JournalRoute
  '/visit': typeof VisitRoute
  '/journal_/$slug': typeof JournalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artisans'
    | '/collection'
    | '/house-of-craft'
    | '/journal'
    | '/visit'
    | '/journal/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artisans'
    | '/collection'
    | '/house-of-craft'
    | '/journal'
    | '/visit'
    | '/journal/$slug'
  id:
    | '__root__'
    | '/'
    | '/artisans'
    | '/collection'
    | '/house-of-craft'
    | '/journal'
    | '/visit'
    | '/journal_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtisansRoute: typeof ArtisansRoute
  CollectionRoute: typeof CollectionRoute
  HouseOfCraftRoute: typeof HouseOfCraftRoute
  JournalRoute: typeof JournalRoute
  VisitRoute: typeof VisitRoute
  JournalSlugRoute: typeof JournalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-of-craft': {
      id: '/house-of-craft'
      path: '/house-of-craft'
      fullPath: '/house-of-craft'
      preLoaderRoute: typeof HouseOfCraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisans': {
      id: '/artisans'
      path: '/artisans'
      fullPath: '/artisans'
      preLoaderRoute: typeof ArtisansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal_/$slug': {
      id: '/journal_/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtisansRoute: ArtisansRoute,
  CollectionRoute: CollectionRoute,
  HouseOfCraftRoute: HouseOfCraftRoute,
  JournalRoute: JournalRoute,
  VisitRoute: VisitRoute,
  JournalSlugRoute: JournalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
